spring:
  datasource:
    url: jdbc:mysql://localhost:3306/livraria
    username: root
    password: 011097
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
